
export const LOGIN_ADMIN='LOGIN_ADMIN'
export const LOGIN_ADMIN_SUCCESS='LOGIN_ADMIN_SUCCESS'
export const LOGIN_ADMIN_FAIL='LOGIN_ADMIN_FAIL'

export const GET_AUTH_ADMIN="GET_AUTH_ADMIN"
export const GET_AUTH_ADMIN_SUCCESS="GET_AUTH_ADMIN_SUCCESS"
export const GET_AUTH_ADMIN_FAIL="GET_AUTH_ADMIN_FAIL"


export const GET_PRODUCT="GET_PRODUCT"



export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS"







